### ISSUE TITLE
MonsterBlocks causes CSS issue with Plut*** mod

### ISSUE THREAD

**Issue by apoapostolov** [zeel01/MonsterBlocks#1]
Plut*** 1.4.1 + Monsterblocks. Plut*** uses the UI tweak Compact Header Buttons. It can be found in Plut*** settings in Journal, UI tab (bottom on left list). What is caused is that MonsterBlock extends the red X button on the whole length of a window. This affects not only MonsterBlocks but all other sheets. See below: 

![image](https://user-images.githubusercontent.com/4083812/87666766-e24ab480-c771-11ea-9dcf-6d75e30d9f37.png)

![image](https://user-images.githubusercontent.com/4083812/87666788-eb3b8600-c771-11ea-9ac1-b1321eea5e44.png)

Plut*** has many functionalities but its UI tweaks are invaluable and I would love to be able to keep using them.

**Comment by zeel01** [comment]
I have a solution that I believe will remedy this. I need to ensure that there aren't any side-effects, and then it will be included in the next release.
