### ISSUE TITLE
The number of limited uses of a feature are not directly editable from the character sheet

### ISSUE THREAD

**Issue by DrYoshiyahu** [zeel01/MonsterBlocks#102]
I believe this is a bug, because the text itself in the stat block *is* editable, but the variable behind the scenes does not change.

In other words, you can type `(3, 3/Day)` into the stat block, but the actual uses remaining will be `0, 3/Day`, which, of course, means that trying to use the feature, even when the *stat block* says there are three uses remaining, will not work—the user will be told there are no uses remaining.

**Comment by zeel01** [comment]
Well that's not good. Can you verify this behavior with no other modules enabled? And are there any errors in the console when you edit the values?

**Comment by DrYoshiyahu** [comment]
Yep, I turned off all other modules and there was no improvement.

And yes, there is an error.
![image](https://user-images.githubusercontent.com/14756430/129468697-75d875d0-cd3e-4bf7-83e1-ef2a3405c2bf.png)

**Comment by DrYoshiyahu** [comment]
A similar, but different issue, is also affecting the recharge feature. Rolling the number to recharge a feature doesn't change any variables behind the scenes, and the ability is still disabled.
![image](https://user-images.githubusercontent.com/14756430/129482338-fb471dbc-5556-429e-864b-81f511995b56.png)
