### ISSUE TITLE
Using `systems` rather than `system`

### ISSUE THREAD

**Issue by arcanistzed** [zeel01/MonsterBlocks#108]
When launching Foundry with Monster Blocks installed you get this message: ```Package monsterblock is using the old "systems" manifest key where a "system" key is expected```

```json
"systems": ["dnd5e"],
```
should be changed to
```json
"system": ["dnd5e"],
```

**Comment by zeel01** [comment]
Oh, this 🙄
Keep forgetting to fix the little things...
