### ISSUE TITLE
Clicking image now opens tokenizer

### ISSUE THREAD

**Issue by Pyroman2xxx** [zeel01/MonsterBlocks#11]
One of my favorite features of MonsterBlocks is breaking with 2.0.1. Clicking on the image from the rendered block is opening tokenizer instead of displaying the image so that I can share it with the players.

Without tokenizer activated, it is behaving as it did before by showing the image. Is there a setting that can be added to prevent tokenizer from appearing when clicking the image?

If I want tokenizer to open, I can just click the settings gear and select 'Open VTTA Tokenizer'.

Thank you! Loving the changes in 2.x

**Comment by zeel01** [comment]
Yeah, this is something I have to fix, or possibly something that VTTA Assets could fix. It's an unintended consequence of being able to edit the image now, suddenly tokenizer recognizes it as an editable image and hooks in its click handler.

**Comment by zeel01** [comment]
This will be fixed in the next release.
