### ISSUE TITLE
Uncaught SyntaxError: Identifier 'InputAdapter' has already been declared

### ISSUE THREAD

**Issue by arcanistzed** [zeel01/MonsterBlocks#111]
This appears on load in the console:
![Screenshot from 2021-08-23 18-44-28](https://user-images.githubusercontent.com/82790112/130528866-f5dcbad3-143e-4077-9956-707a666eb4ad.png)

**Comment by zeel01** [comment]
I know...

**Comment by zeel01** [comment]
It's because Input Expressions and Monster Blocks share some code. And I've been incredibly lazy about de-duplication.
