### ISSUE TITLE
Walking speed of zero, and flying (hover) speeds do not display appropriately

### ISSUE THREAD

**Issue by DrYoshiyahu** [zeel01/MonsterBlocks#112]
Some creatures have movement speeds of 0 ft., which does not render correctly on Monster Blocks. Instead of "0 ft.," which is the convention, it simply renders no text at all, which also leaves an ugly comma.

**Monster Blocks:**
![image](https://user-images.githubusercontent.com/14756430/130544982-629e1228-6f07-4121-9ec0-d3c0097b8e60.png)

**D&D Beyond:**
![image](https://user-images.githubusercontent.com/14756430/130545268-e17aa376-69f7-488a-ae7b-7e2b293ef370.png)

Also, why "hover X ft." and not "fly X ft. (hover)"? The latter is the convention.

**Comment by zeel01** [comment]
Hmm, yeah, the 0 speed *should* render as such. I'm not sure why it isn't, but I could swear it worked right when speed originally got refactored 🤨

Hover... yeah, idk how I missed that. But that's certainly how it looks in the Monster Manual.

![image](https://user-images.githubusercontent.com/1721836/130556940-d96bb470-c94e-40f9-a6f9-f1e00c30196e.png)
