### ISSUE TITLE
MonsterBlocks stopped working after upgrade to 0.8.9

### ISSUE THREAD

**Issue by KJTailor** [zeel01/MonsterBlocks#113]
I recently upgraded from 0.8.8 to 0.8.9 and since Monster Blocks is not working anymore. It is installed properly in the setup menu, but it doesn't show up in the module manager in-game anymore and hence can't be activated or disabled.

I'm happy to provide any further information that's needed, I just would love to get it going again.

Cheers.

**Comment by zeel01** [comment]
What version of `dnd5e` do you have installed?

**Comment by KJTailor** [comment]
I held off on the most recent DnD5e system upgrade out of worry it might break things if I upgrade too hastily. Guess the opposite has happened now. I will upgrade it and let you know if that fixes it.

Thank you, didn't even consider that might be the problem.

**Comment by zeel01** [comment]
The new Armor Class system means the sheet is no longer compatible with the older version. To prevent errors or data corruption, Foundry automatically disables it.
