### ISSUE TITLE
Support Minor QOL

### ISSUE THREAD

**Issue by akrigline** [zeel01/MonsterBlocks#12]
Similar but different to Better Rolls, [Minor QOL](https://gitlab.com/tposney/minor-qol/-/tree/master) is another common automation suite for combat.

It would be excellent if the way in which rolls for attack items were initiated would mesh with the Minor QOL way as well.

**Comment by zeel01** [comment]
This is something I will look into, though I can't make guarantees. Many mods like that can be tricky to integrate, and it may be easier for that developer to add support for a particular sheet than the reverse. Better Rolls support basically doubles the amount of code for handling rolls, and I likely wouldn't have bothered with it if I had realized how much extra code it would take when I started.

**Comment by akrigline** [comment]
I did some digging here. It turns out that Minor-QOL attempted to support this, but had a small bug in where the bindings happen. I've submitted a [PR](https://gitlab.com/tposney/minor-qol/-/merge_requests/16) to fix this on their end. I believe this issue can be closed.
