### ISSUE TITLE
disable feature information on hover

### ISSUE THREAD

**Issue by maxobremer** [zeel01/MonsterBlocks#120]
Would it be possible to implement a feature to disable the feature where a description of an item is opened when you hover over said item? I'd rather just click on it to open the feature manually then it opens and covers up part of the sheet when i am moving my mouse with the intend to use the feature below it.

**Comment by zeel01** [comment]
It sounds like you have enabled the "Compact Features" option. You can disable this by default in the module settings, or per-actor from the cog menu.

This feature is not generally enabled by default.


![image](https://user-images.githubusercontent.com/1721836/134695092-8e3390f4-3711-4c89-bff4-0539cd9222a8.png)
