### ISSUE TITLE
Weapon damage not using @mod in auto-generated damage block

### ISSUE THREAD

**Issue by brother-oak** [zeel01/MonsterBlocks#123]
If I have a monster that uses a weapon, that weapon invariably uses the "@mod" in its damage formula. 
When MB auto-generates the attack description for this weapon, the @mod is not calculated, and is ignored. This gives the incorrect description, and also causes the damage roll to ignore any bonuses, if the damage is rolled separately (by clicking on the roll in the text block). If the entire attack is rolled in one go (e.g. click on "Scimitar"), then the damage IS correctly rolled.

Example - this goblin was dragged in from the SRD. Its description (secret) text is correct, but the auto-generated text for scimitar and shortbow attacks have the incorrect damage formulae, as the @mod is ignored.

![image](https://user-images.githubusercontent.com/66773832/136816952-8c7a2dbc-c005-43ff-b133-fa2cf7f5fceb.png)

**Comment by brother-oak** [comment]
Surprisingly, the average damage is calculated correctly, though!

**Comment by zeel01** [comment]
Interesting, what version of Monster Blocks, of `dnd5e`, and of Foundry are installed? Something may have changed in the last system update.

**Comment by brother-oak** [comment]
Latest version of everything, so yep - could be the latest dnd 5e system that changed it (as I only just installed that). Have only just started using MB in earnest so wouldn't have seen if it worked in a previous version.

Foundry v0.8.9
DnD 5e v1.5.2
MB v3.1.1
