### ISSUE TITLE
The Included Actor Doesn't Work

### ISSUE THREAD

**Issue by melance** [zeel01/MonsterBlocks#13]
When I change the sheet for this actor, the sheet completely disappears and won't show back up.  I'm assuming this is causing an exception but it's not being displayed.

[fvtt-Actor-Boggle.json.txt](https://github.com/zeel01/MonsterBlocks/files/5164524/fvtt-Actor-Boggle.json.txt)

**Comment by zeel01** [comment]
Interesting, I'll give it a look.

**Comment by zeel01** [comment]
Interesting, that looks like it was imported from D&D Beyond? The hit point formula appears to contain a character that *looks* like a typical `-` but isn't. It appears to be a Unicode 0x2212 `−` which may appear identical, or slightly wider than a standard minus/dash.

The Javascript engine doesn't recognize this character as a valid operator (it's not!), which causes an error in the math function. I assume this was imported with VTTA DNDBeyond? He might need to fix this issue if it's importing invalid characters.

However, obviously throwing an error and not rendering is a problem, so I will make a change to Monster Blocks in the next version that should more gracefully handle this.

**Comment by melance** [comment]
I see, it's the old "Greek Question mark" issue.  Thanks for looking into it.

**Comment by zeel01** [comment]
I have reported this issue both to VTTA Beyond and Foundry core, and the next version of Monster Blocks will handle it gracefully without failing to render.

Unfortunately any actors with this issue will need manually edited, or re-imported when VTTA Beyond is updated.
