### ISSUE TITLE
Do not show Actions heading when no action are present

### ISSUE THREAD

**Issue by jeremyregnerus** [zeel01/MonsterBlocks#145]
Do not show the Action Header when there are no actions for the NPC to take. This can happen with very low level NPCs, or NPCs that are basic stat blocks.

I have a solution for this in my working copy. It however requires the implementation of #144 to solve this. So I'm not sure how I would go about creating a PR / commit for this without that first in place. Do I just create another PR that also has those same changes in it?

**Comment by zeel01** [comment]
I merged the other two, so you should be fine to open a new one for this.

**Comment by zeel01** [comment]
Ideally set this:

![image](https://user-images.githubusercontent.com/1721836/154617420-1e71d4a8-4d45-4114-a38c-74b7faf185aa.png)

So that the issue auto-closes.
