### ISSUE TITLE
At-will spells not appearing in Spellcasting text

### ISSUE THREAD

**Issue by jeremyregnerus** [zeel01/MonsterBlocks#147]
I'm pretty sure spellcasters like the Archmage used to show their At-will spells within the spellcasting text.

![image](https://user-images.githubusercontent.com/7407481/154847709-d276f09e-c068-4034-8838-758549d8a631.png)

These do not appear there anymore.

![image](https://user-images.githubusercontent.com/7407481/154847733-28f95784-532a-4ec8-b1a9-0de7f31dd3e7.png)

Looks to be a change from https://github.com/zeel01/MonsterBlocks/commit/0c867c4fd972d2318a749af88d80f8aff77edf94

**Comment by zeel01** [comment]
Hell. So something in the refactor broke it, that's gonna suck to diagnose. Thanks for the report though.

**Comment by jeremyregnerus** [comment]
I found it, I'm just verifying if this was happening elsewhere, if the fix causes any issues, and looking at a potential sort order issue for at-will spells for Innate Spellcasters.

**Comment by jeremyregnerus** [comment]
This issue is resolved here - https://github.com/jeremyregnerus/MonsterBlocks/commit/9944be34151043bfb585e24b350f856a3e66e792

I want to make sure that changing `data.preparation` to `data.data.preparation` in `isSpellcaster()`, `isInnateSpellcaster()` and `isWarlock()` doesn't break anything.

Also, seeing that at-will spells in innate spellcasters are appearing at the end of the spell list, not at the beginning.

**Comment by jeremyregnerus** [comment]
> I want to make sure that changing `data.preparation` to `data.data.preparation` in `isSpellcaster()`, `isInnateSpellcaster()` and `isWarlock()` doesn't break anything.

It looks like `HasAtWillSpells()` is the only one of these methods still being used.

**Comment by jeremyregnerus** [comment]
> Also, seeing that at-will spells in innate spellcasters are appearing at the end of the spell list, not at the beginning.

It seems if I edit / open the spells in the current atwill list and close them, it resolves the correct position in the spell list.
