### ISSUE TITLE
Innate Spellcasting not reflecting available uses

### ISSUE THREAD

**Issue by Pyroman2xxx** [zeel01/MonsterBlocks#15]
The Innate Spellcasting spells show the max uses but do not reflect the available uses in the same way that regular spellcasting shows the available slots.

Edit: Now that I think about this further, it is likely because you would have to display each spell individually for current/max uses. I am not sure the best approach for this would be. Maybe a single Integer in parenthesis after each spell name for innate spells that have limited uses.

**Comment by zeel01** [comment]
It actually does work that way, but requires a bit of extra configuration for the spell to track the right resource.

![image](https://user-images.githubusercontent.com/1721836/92139454-bea10380-eddd-11ea-8647-49c3f51bfb9b.png)
![image](https://user-images.githubusercontent.com/1721836/92139526-db3d3b80-eddd-11ea-80e1-f93f976bae6a.png)
If "limited uses" is set correctly, you still need to specify that the spell *consumes* a resource. The drop down will list all spells and items the Actor has that have limited uses.

This is a bit counterintuitive, but it's the way the 5e system is set up. Once you set the right resource for the spell though, the current available uses will appear next to it in parenthesis. It's unfortunately a little bit of a poor click-target, but it works.

The same works for items that consume other resources, like ammo. You can set up a bow to use arrows, and an arrow count will display next to it - however this mean you need to give the actor some arrows as an item.

Unfortunately, most SRD and imported creatures are missing some of these important settings. They don't get any ammo allotted, the spells don't have their resources set, etc. This isn't something I can reasonably fix, at least not with Monster Blocks.

**Comment by Pyroman2xxx** [comment]
Great, thank you for explaining that.

**Comment by Pyroman2xxx** [comment]
Actually, now that I set it up this way, it appears to be using double charges now. With Resource Consumption set it is using it twice; once for the initial use and then again because of resource consumption.

**Comment by zeel01** [comment]
It's possible that the way I'm handling this isn't correct. But in my tests previously it wasn't consuming resources if they were set.

**Comment by zeel01** [comment]
This should be fixed in the next release.
