### ISSUE TITLE
Saving throws bug, resistances option missing

### ISSUE THREAD

**Issue by figotech** [zeel01/MonsterBlocks#16]
Hi, first of all with all the added features this is by far the best NPC Sheet.

While fixing some monsters I found out that Saving throws edit is bugged: it doesn't update its checked status when changing it and you need to go to default sheet to fix them It will do the check uncheck to the template, but since it doesnt update you can toggle them (I noticed them when removing saving throsws from a monster).
I think its a recent addition, but there is a new "Non-magical physical attacks" option in resistances and immunities and it doesnt show on the edit dropdown.

With those fixed the only thing I have to switch to the original sheet for is to update the page! (source field)
Great work!

**Comment by zeel01** [comment]
I can't reproduce the Saving Throws issue.

**Comment by zeel01** [comment]
I have corrected the missing Non-Magical physical option, it will be available in the next release.
