### ISSUE TITLE
Armor description next to Armor Class

### ISSUE THREAD

**Issue by ravenx99** [zeel01/MonsterBlocks#18]
In the MM stat blocks, there is often a description of the type of armor next to the AC entry... for Goblin:

**Armor Class 15 (leather armor, shield)**

I really like being able to see that the goblin has a shield... I make variant goblins with different weapons, and goblins with spears can drop their shields to use the spear (a versatile weapon) two-handed.  Or if I create a goblin with something better than leather armor (or one with no armor) it's clear why the AC differs from the norm.
It would be really cool if this could be incorporated.  I like Monster Blocks way better than a character sheet with data spread out over tabs.

**Comment by zeel01** [comment]
I fully agree, but it's a limitation of the data Foundry 5e supplies. AFAIK, there isn't a proper "armor description" on the actors, and I don't really want to add new fields. If this ever changes, I will add it to Monster Blocks right away though, as it is an annoying omission.

**Comment by ravenx99** [comment]
I was afraid that would be the case (I'm a systems engineer and sometimes developer), but you never know if you don't ask.  Thanks for the prompt feedback!

**Comment by zeel01** [comment]
Closing for now, maybe someday.
