### ISSUE TITLE
Foundry V10 Support

### ISSUE THREAD

**Issue by gaffdninja** [zeel01/MonsterBlocks#198]
Will this module be updated for version 10 support?  My games are not the same without them.  In any case keep up the good work :)

**Comment by zeel01** [comment]
It will.

**Comment by DarioRomano** [comment]
> It will.

Thank you for the information, and another big thank you for creating and maintaining this module. It's great.

**Comment by thjhoekstra** [comment]
Is there a large difference between V9 and V10 for foundry? I can't recall that V8 to V9 made the modules broken, or people were just fast with updating.

**Comment by DarioRomano** [comment]
> Is there a large difference between V9 and V10 for foundry? I can't recall that V8 to V9 made the modules broken, or people were just fast with updating.

There have been a number of changes regarding the appearance of sheets in V10, therefore this module specifically is affected.

**Comment by friction1** [comment]
Does anyone know if the owner has given a timeline for the update? I tried to run a session without this module last night and combat was a disaster. I understand the owner is a volunteer, not trying to rush - just wondering. Thanks for a great module :)

**Comment by zeel01** [comment]
I can't really give a timeline, i have very little time to work on these things lately, and there's a lot to do. An update will come, but I can't really guess how soon.

**Comment by friction1** [comment]
> I can't really give a timeline, i have very little time to work on these things lately, and there's a lot to do. An update will come, but I can't really guess how soon.

Thanks for your reply. Is there anything we can do to support you financially to help prioritize the update? Maybe others would be down to chip in.

**Comment by davelamorte** [comment]
> > I can't really give a timeline, i have very little time to work on these things lately, and there's a lot to do. An update will come, but I can't really guess how soon.
> 
> Thanks for your reply. Is there anything we can do to support you financially to help prioritize the update? Maybe others would be down to chip in.

Definitely! Well worth it!

**Comment by Rencos1** [comment]
I just submitted a pull request that support v10. I didn't test extensively but it seems to work pretty well.

**Comment by zeel01** [comment]
I will take a look

**Comment by JanHoos** [comment]
Thank you Zeel! I loved using this module for my monsters. It made it so easy to read them and to adjust them :-) 

Thanks for trying to help fix it as well Rencos1 :D

**Comment by friction1** [comment]
I updated the .json and script files based on Rencos1's pull request in my game and all standard monsters seem to work fine. A few (not all) of my homebrew monsters or things I've imported from dndbeyond homebrew won't open. Happy to provide a few examples for troubleshooting if it helps.

**Comment by zeel01** [comment]
@friction1 If you could provide error messages and statblocks as comments on the pull request that would be helpful.

Additionally, I really want to make at least one release that's cross compatible between v9 and v10 if at all possible, so that's something to keep in mind as well.

**Comment by friction1** [comment]
> @friction1 If you could provide error messages and statblocks as comments on the pull request that would be helpful.
> 
> Additionally, I really want to make at least one release that's cross compatible between v9 and v10 if at all possible, so that's something to keep in mind as well.

Okay I've added some!

**Comment by JanHoos** [comment]
Awesome! Thanks for updating this to v10! <3

**Comment by davelamorte** [comment]
Thank you! Much appreciated!
