### ISSUE TITLE
Show Artwork to Players functionality

### ISSUE THREAD

**Issue by apoapostolov** [zeel01/MonsterBlocks#2]
When hovering on a MonsterBlock artwork of a monster, a button in a corner to open the actor avatar of the monster as image journal so that it can be shown to players. This is similar to right click on an actor and show image to players option.

**Comment by zeel01** [comment]
Not a bad idea, I'll add it to my list of things to look into.

**Comment by shawndibble** [comment]
VTTA DNDBeyond Module has this functionality on images in the journal. I wonder if you can use something from their code to do the same.
