### ISSUE TITLE
Renaming a NPC by changing the name in monster blocks doesn't change the name.

### ISSUE THREAD

**Issue by thjhoekstra** [zeel01/MonsterBlocks#200]

**Comment by zeel01** [comment]
What version of Monster Blocks, dnd5e, and Foundry?

Are there any error messages?

**Comment by thjhoekstra** [comment]
All versions are up to date as of today, updated to see if the issue persists, and it seems to
I get no warning or errors that I can see

monster blocks: 3.3.1
dnd5e: 2.0.3
foundry: 10.287

**Comment by thjhoekstra** [comment]
![afbeelding](https://user-images.githubusercontent.com/25770795/194871523-b0b00d25-f66e-4308-9099-875fa34f4cd9.png)
 actually, it seems that I do get some

**Comment by zeel01** [comment]
Those are all only compatibility warnings (because of changes between v9
and v10).

**Comment by JanHoos** [comment]
Hi! 

To add to this, changing HP formula or the attributes (STR, DEX, etc.) also don't save.

**Comment by PantsDragon** [comment]
> What version of Monster Blocks, dnd5e, and Foundry?
> 
> Are there any error messages?

Running into this same issue. Here is the console output that occurs when I double click a token to view the sheet:

```
commons.js:1703 Error: You are using FormDataExtended#toObject which is deprecated in favor of FormDataExtended#object
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692)
    at FormData.toObject (foundry.js:58541)
    at MonsterBlock5e._getSubmitData (MonsterBlock5e.js:198)
    at MonsterBlock5e._onSubmit (foundry.js:5864)
    at MonsterBlock5e.submit (foundry.js:6195)
    at MonsterBlock5e.close (foundry.js:6167)
    at MonsterBlock5e.close (foundry.js:6295)
    at MonsterBlock5e.close (foundry.js:60870)
    at MonsterBlock5e.close (MonsterBlock5e.js:1135)
    at Object.onclick (foundry.js:5290)
    at HTMLAnchorElement.<anonymous> (foundry.js:5198)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.y.handle (jquery.min.js:2)
logCompatibilityWarning @ commons.js:1703
toObject @ foundry.js:58541
_getSubmitData @ MonsterBlock5e.js:198
_onSubmit @ foundry.js:5864
submit @ foundry.js:6195
close @ foundry.js:6167
close @ foundry.js:6295
close @ foundry.js:60870
close @ MonsterBlock5e.js:1135
onclick @ foundry.js:5290
(anonymous) @ foundry.js:5198
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

Foundry version 10.288
dnd5e: 2.0.3
Monster Blocks 3.3.1

**Comment by nschoenwald** [comment]
I have the same issue. No errors, but changes just don't get saved. I have to change to default sheet to make changes.

**Comment by teripper** [comment]
Same issue here with same module, 5e, and Foundry versions.

**Comment by Zamrod** [comment]
This is still happening. Names can't be changed in the Monster Block sheet
