### ISSUE TITLE
dnd5e 2.1.1 Compatibility

### ISSUE THREAD

**Issue by friction1** [zeel01/MonsterBlocks#201]
<img width="551" alt="Screenshot 2023-01-11 at 4 52 52 PM" src="https://user-images.githubusercontent.com/11384891/211925705-42383c35-aafb-4ac0-99e8-7ad0fffc496a.png">

**Comment by zeel01** [comment]
Darn it.

**Comment by Nupky** [comment]
Someone beat me to it :P Thanks a bunch @zeel01 -- honestly my favorite plugin!

**Comment by Benethor92** [comment]
Any chance to get it fixed until next weekend? Ive got a DnD game and honestly cant really play whithout your addon anymore, so i need to look for a way to roleback if there is no possible fix anytime soon :(

**Comment by zeel01** [comment]
I'll try too look at it this weekend. It's probably something small, usually is.

**Comment by zeel01** [comment]
Should be resolved in the next release.
