### ISSUE TITLE
All spellslots shown as level 1

### ISSUE THREAD

**Issue by Benethor92** [zeel01/MonsterBlocks#204]
I am really sorry to bother you again, but new update, new bug :D
Its a minor one this time, nothing game breaking. But on the monster blocks all spellslots are shown as level 1. Even though they arent and are correctly consumed as a higher tier spell slot when a higher level spell is being casted:

![grafik](https://user-images.githubusercontent.com/111077874/213657466-b37684f2-eb4e-4d98-b891-81621ff9f4c4.png)
![grafik](https://user-images.githubusercontent.com/111077874/213657504-c7674052-f2c9-4386-a03d-2d9a3beae1b8.png)

So its only a visual bug as far as i see it. Tested on multiple spellcasting actors (which finally work again, thanks for that!)

**Comment by Benethor92** [comment]
![grafik](https://user-images.githubusercontent.com/111077874/213757202-9212630f-ac31-4b41-98f4-1a15dd6ba7e3.png)
Similar problems with skills not showing correctly

**Comment by zeel01** [comment]
Should be fixed in v3.3.4
