### ISSUE TITLE
Bonus Actions and Reactions don't appear to show up anymore

### ISSUE THREAD

**Issue by evan-rash** [zeel01/MonsterBlocks#205]
Wanted to start off by saying thanks so much for creating this mod, it's really a lifesaver!!!

After the new update, Bonus Action and Reaction features don't seem to get their own section anymore

![image](https://user-images.githubusercontent.com/5857034/213798224-64ab46cd-d18b-4512-92c5-29cd7216a307.png)

**Comment by zeel01** [comment]
Should be fixed in v3.3.4
