### ISSUE TITLE
Monster sheets won't open

### ISSUE THREAD

**Issue by KJTailor** [zeel01/MonsterBlocks#207]
The following issue occured yesterday:
Anything that was a monster block from this module, wouldn't open the character sheet yesterday.
Any PC character sheet worked fine, it only affected MonsterBlocks.
I could temporary alleviate the issue, by turning MonsterBlocks off.

I will run a few tests to possibly find if it is an issue on my side (bad module interaction, etc.) later today, and I will also run "find the cultprit" to see what it could be

**Comment by zeel01** [comment]
We're there any errors in thd console? What module/system/core versions were you using?

**Comment by KJTailor** [comment]
Alright, here is some extra information.
First off, the error in the console. When _MonsterBlocks_ is active and I try to open a sheet that is supposed to be a monster block, this error message appears in the console:
![image](https://user-images.githubusercontent.com/87787745/215422881-3bb9eb52-8979-4e6b-8b78-e7c65a4961fc.png)

Module is version 3.3.5, here is the rest:
![image](https://user-images.githubusercontent.com/87787745/215423065-0c79556f-f349-40b3-a889-54af0fb11131.png)

Could it be because I have yet to update the 5E system version?

**Comment by zeel01** [comment]
It looks like you need to update dnd5e, or downgrade Monster Blocks to 3.3.1, the error you posted is one that would be expected with too new a version of MB with an old system version.
