### ISSUE TITLE
Compatibility with Foundry V11 and dnd5e 2.2.0

### ISSUE THREAD

**Issue by nschoenwald** [zeel01/MonsterBlocks#211]
Will this module be updated for the new releases of foundry and dnd5e? It's my favorite npc sheet and I would love to keep using it!

**Comment by zeel01** [comment]
Yes, it will be updated. I can't guarantee a timeline yet. The v11 release may be marked as "stable" but I would _highly_ discourage updating any ongoing campaigns to v11 for at least a few weeks to account for bugs and various module updates.

**Comment by friction1** [comment]
If this is helpful, I've updated dnd5e but still running V11. I have the following errors from Monster Blocks.
<img width="1059" alt="Screenshot 2023-05-25 at 4 48 44 PM" src="https://github.com/zeel01/MonsterBlocks/assets/11384891/b40023a8-feda-48fc-a746-ef48cfb5c033">
<img width="1073" alt="Screenshot 2023-05-25 at 4 49 28 PM" src="https://github.com/zeel01/MonsterBlocks/assets/11384891/12561ea1-4c07-4af2-aad6-603ec6c274e0">
<img width="1060" alt="Screenshot 2023-05-25 at 4 49 05 PM" src="https://github.com/zeel01/MonsterBlocks/assets/11384891/37ccd869-bdae-479d-8088-01ce8abc19f0">

**Comment by evan-rash** [comment]
@zeel01 - unfortunately it looks like updating to dnd5e 2.2.0 causes some issues (even staying on foundry v10)

![image](https://github.com/zeel01/MonsterBlocks/assets/5857034/ad62b302-4a59-47f0-af93-24231e6482e9)

**Comment by evan-rash** [comment]
@zeel01 - do you accept PRs? I started trying to debug the issues and I've been slowly working my way through all the places that have to be refactored because of the changes to `data.*`

**Comment by Benethor92** [comment]
Any news on updates for v11? I just updated and out of 50+ modules this is the only one still not working with v11 :/

**Comment by kajishun** [comment]
i wish! i love this module!

**Comment by zeel01** [comment]
Merged https://github.com/zeel01/MonsterBlocks/pull/212 and published release.
