### ISSUE TITLE
Sheet does not render

### ISSUE THREAD

**Issue by Ematusz** [zeel01/MonsterBlocks#213]
I am trying to install this module. It looks like it will be super useful. Unfortunately, I am finding that the sheet does not render at all. I click the actor and nothing happens.

Foundry VTT version: 10
D&D e5 version : 2.2.1

In the dev console I see the following errors. 
<img width="686" alt="image" src="https://github.com/zeel01/MonsterBlocks/assets/20713043/b8c9ec28-0461-4738-8f4d-375de631b4d0">
<img width="422" alt="image" src="https://github.com/zeel01/MonsterBlocks/assets/20713043/27632d3c-7e66-4ca8-acf3-4547065335b1">

**Comment by zeel01** [comment]
Duplicates #211
