### ISSUE TITLE
Switching to MonsterBlocks closes, sheet, won't re-open

### ISSUE THREAD

**Issue by NeatoJiraffe** [zeel01/MonsterBlocks#214]
Foundry Virtual Tabletop: Version 10
Build: 291
DnD5e - 5th Edition System: 2.2.1
Active Modules: 2  (Monster Blocks, Math.js)

I entered a new world, enabled just MonsterBlocks and the Math.js dependency. Used a dnd5e SRD monster and imported the Adult Black Dragon. Opened the sheet in default Foundry sheet, switched to Monster Blocks for the sheet type and the sheet closes. When trying to re-open, nothing happens. I check console and there are 9 warnings and 1 error.

Here is the pastebin for it, hope that helps. Let me know if images are easier! https://pastebin.com/zm4F6eb8

**Comment by rbaines** [comment]
I suspect this is the same issue as the below.   I am seeing the same behavior.

[211](https://github.com/zeel01/MonsterBlocks/issues/211)

**Comment by zeel01** [comment]
Resolved via #211
