### ISSUE TITLE
Senses show "null" instead of correct unit

### ISSUE THREAD

**Issue by nschoenwald** [zeel01/MonsterBlocks#218]
<img width="392" alt="image" src="https://github.com/zeel01/MonsterBlocks/assets/72390280/f005e458-d60d-479d-b7d8-bd935387d884">

It briefly works when you manually set the unit in the default sheet and then switch to Monster Blocks, but it breaks again the next time you open the sheet via Monster Blocks.

**Comment by zeel01** [comment]
Something really fishy is happening here. I was able to reproduce this, but it seems like something is being mutated where it shouldn't be. I'll have to track down where this is taking place.

**Comment by zeel01** [comment]
Resolved via #221
