### ISSUE TITLE
Sheet not opening in dnd5e 3.0.0

### ISSUE THREAD

**Issue by Urkaz** [zeel01/MonsterBlocks#219]
Due to the new dnd5e 3.0.0 update the sheet doesn't render and displays an error message in the browser console:
![image](https://github.com/zeel01/MonsterBlocks/assets/521864/0ecb9769-8310-4363-8428-0cafafdcdb82)

I'm using:

* Foundry v11.315
* System D&D 3.0.0
* MonsterBlocks 3.4.0

**Comment by friction1** [comment]
Same. Following and hoping someone can find the fixes. In the coming months, something like this module may become core hopefully.

**Comment by zeel01** [comment]
Figures there would be issues in such a huge update.

**Comment by Aedif** [comment]
`CONFIG.DND5E.damageResistanceTypes` just needs to be replaced with `CONFIG.DND5E.damageTypes` I think

**Comment by zeel01** [comment]
Yeah, if they changed that name it would certainly explain the issue. I'll try to take a look at it after work if I get the opportunity.

**Comment by zeel01** [comment]
Resolved via f0c7f9f2fa379b0892ccb83fb22ba0c3465e2d43. Will be included in the next update.
