### ISSUE TITLE
Senses is Null Error

### ISSUE THREAD

**Issue by DivertedCircle** [zeel01/MonsterBlocks#22]
Saw this mentioned on the Discord already. Seems if a monster doesn't have senses entered you get a 'senses is null' error when trying to open the sheet and it refuses to open.

![image](https://user-images.githubusercontent.com/26470570/97121065-479f3180-16e1-11eb-88b7-ae15e6c979ab.png)

**Comment by zeel01** [comment]
https://github.com/zeel01/MonsterBlocks/issues/21
