### ISSUE TITLE
MonsterBlocks on 12.327 and DnD5e 3.2.1 not working at all.

### ISSUE THREAD

**Issue by Cergorach** [zeel01/MonsterBlocks#234]
Foundry VTT: 12.327
DnD5e: 3.2.1
Monster Blocks: 3.4.0

I know this isn't supported (yet), but just testing what is and isn't working on v12 and Monster Blocks definitely isn't working (when selected, no NPC sheet at all anymore). So besides the ton of deprecation warnings, we got the following errors:
![image](https://github.com/zeel01/MonsterBlocks/assets/173634376/2fcd01dc-f453-4ff0-a023-bd504348bfa7)
![image](https://github.com/zeel01/MonsterBlocks/assets/173634376/d591f290-ca16-4ead-af7e-132891bd2e37)

Just editing out line# 347 in MonsterBlock5e.js atleast shows the Monster Blocks NPC sheet again.
`// this.getTraitChecklist(id, menu, `system.traits.${id}`, "damage-type", CONFIG.DND5E.damageResistanceTypes);`

That 'fixes' the error, but leaves a ton of deprecation warnings and we're missing a ton of info with the '[object Promise]' bug #233.

Note: I'm not a programmer/developer, just a monkey with a keyboard.

**Comment by friction1** [comment]
@zeel01 do you have any timeline for working on this? I would be happy to help fundraise to compensate you for your time to get monster blocks updated. You're a champion to our community.

**Comment by zeel01** [comment]
@friction1 I don't unfortunately, and compensation isn't what I'm lacking. I really appreciate your willingness to contribute though.

Unrelatedly, this issue appears to be the same as #233 so I'll close this one as a duplicate.
