### ISSUE TITLE
Monster Block shows coding

### ISSUE THREAD

**Issue by Wrightstuff169** [zeel01/MonsterBlocks#235]
Hi, I'm new to foundry with absolutely no programming experience and didnt know if what i am seeing below is a bug or simply something i'm not doing correctly
![Screenshot 2024-07-03 221217](https://github.com/zeel01/MonsterBlocks/assets/174655677/5a890915-b001-44ed-91bf-eaf871854b8d)

**Comment by zeel01** [comment]
This is the same issue as #233. Changes to Foundry and the 5e system require a pretty big overhaul of the internals of the module.
