### ISSUE TITLE
Code for image sharing in biography

### ISSUE THREAD

**Issue by figotech** [zeel01/MonsterBlocks#25]
As requested the code that can be added at line 1087 of monsterblock.js is:

html.find(".editor-content>>img").click((event) => {
			event.preventDefault();
			let imgSource = event.target.src;
			new ImagePopout(imgSource, {
				title: this.actor.name,
				shareable: true,
				uuid: this.actor.uuid
			}).render(true);
		});

This will allow any image in the biography to be easily shared.

**Comment by zeel01** [comment]
Will be available in the next release.
