### ISSUE TITLE
Switching back to default sheet

### ISSUE THREAD

**Issue by west1778** [zeel01/MonsterBlocks#27]
Pressing "Switch to default sheet" doesn't swap sheet out. Getting some errors as well. 

![image](https://user-images.githubusercontent.com/73608023/98484076-0a579b00-21db-11eb-8dfa-1414eba4f4ce.png)

**Comment by zeel01** [comment]
When you swit h to default, Monster Blocks just re-renders? What sheet is your default sheet? This function doesn't really work right if Monster Blocks *is* the default, so that may be the issue. 

The error message is a benign error that should not cause issue, and the rest is debug output I forget to disable.

**Comment by west1778** [comment]
Well, I was using Monsterblock as the default for NPC's but for Players I'm using Tidy5esheet. I can try and switch that and see if that might be causing it. Just tried switching to a different sheet and it's doing the same thing. It was working yesterday when I tried it though. Please, let me know if you have any other questions. I'm happy to help.

**Comment by zeel01** [comment]
It Monster Blocks the default NPC sheet:
![image](https://user-images.githubusercontent.com/1721836/99215409-c2b7ad00-27a0-11eb-9341-7eb8f701a807.png)
Then the "switch to default" button will switch the sheet to... Monster Blocks. So it will do nothing. 

If the default is something else though, it should work. Can you confirm whether or not it behaves correctly when the default sheet is "Default 5e NPC Sheet". If not, can you look for any errors in the console *other* than the one "Unexpected token u...", that error is a known issue that should not be related.

Currently, I am not able to reproduce an issue where it fails to switch back to a sheet other than itself.

**Comment by west1778** [comment]
Yeah no if it's not the default it will shift it back to whatever sheet I have setup as default. I guess I was thinking that it worked like the sheet button on other sheets where it would give you the option to change to a different sheet then the Monsterblock one. So I see what you're saying. Sorry for the confusion. So don't use it as default if I wanna switch back and forth between sheets. Sorry if you wasted a lot of time on this.

**Comment by zeel01** [comment]
No problem, it should *probably* work differently. The feature is a legacy feature from before editing was possible in Monster Blocks. So it was never a perfect implementation, just enough to make editing a monster less of a PITA.

I'm not sure the ideal way to have it work though, I'm open to suggestions.

**Comment by zeel01** [comment]
Naturally, having it switch the the 5e Default always is an option, but that's also possibly not what people expect. Maybe it should do that *if* Monster Blocks is the default, but otherwise switch to the configured default. That's probably the best way to go.

**Comment by west1778** [comment]
I know absolutely nothing about coding but if you could I would suggestion just making it like other sheets where it gives you the toggle to change the current sheet and apply a new default one. :-/ But I have no idea how or if you could do it with your current sheet :(

**Comment by zeel01** [comment]
Do you have an example of that? I'm not sure I've seen another sheet that implements a way to switch sheets, the standard sheet changing Dialog pictured above is present still with Monster Blocks.

**Comment by west1778** [comment]
OMG I'm an idiot! I never acquired to me to look on that side I just kept clicking on that change to default sheet like an idiot. :( I am so very sorry for wasting your time. :( I guess I got confused cause of the two different ways to change the sheet on there. :( Please forgive me for wasting your time. That works like that. :(

**Comment by zeel01** [comment]
Not a big deal, glad I could help.

**Comment by west1778** [comment]
You're way too kind again thank you now I can go back to using your sheet! YAY

**Comment by zeel01** [comment]
In the next version, "Switch to Default" will switch to the system default sheet if Monster Blocks is the configured default.
