### ISSUE TITLE
Error on converting monsters

### ISSUE THREAD

**Issue by Garemat** [zeel01/MonsterBlocks#28]
![image](https://user-images.githubusercontent.com/9209350/98602511-81268e00-22d8-11eb-81ff-63d21b2a5b39.png)

Hitting the above error when trying to convert to a monster block. I used the default air elemental supplied with the compendium. I checked the walk speed and not sure if because it was 'fly' it made a difference. I tried to convert a few other monsters and I'm getting the same issue

Foundry version: 0.7.6
5e version: 0.98
Monster blocks version: 2.2.8
math.js version: 7.5.1

**Comment by zeel01** [comment]
You need to update your System version or this error will occur. Version 0.99 changed the way speed is stored in the data. The latest System version is 1.1.0
