### ISSUE TITLE
Missing window tab items

### ISSUE THREAD

**Issue by amcvfx** [zeel01/MonsterBlocks#29]
Hey big fan of this npc sheet! I have a problem with tab items along the top being cut off on small monster block sheets though. Prototype Token or Token are often missing from the bar at the top requiring switching to another sheet that can be resized to access them. Is it possible to get those missing tab menus visible in an expandable menu or something?
When I use the Popout window module I am able to resize the Monster Block and see all those missing tab items. Could this resizing also be available in the Foundry window?

**Comment by zeel01** [comment]
Please see the FAQ:

https://github.com/zeel01/MonsterBlocks#q-some-of-the-buttons-on-the-title-bar-are-missing-what-do-i-do

https://github.com/zeel01/MonsterBlocks#q-why-cant-a-resize-the-window
