### ISSUE TITLE
[BUG] missing/broken localization for one theme

### ISSUE THREAD

**Issue by Moerill** [zeel01/MonsterBlocks#30]
![image](https://user-images.githubusercontent.com/26152015/99274859-1bcc2300-282b-11eb-87a8-21ee7aa5b971.png)

One themes name is missing localization (or its broken).

Monster Blocks 2.2.6
FVTT 0.7.7

**Comment by zeel01** [comment]
Looks like I didn't add it to the language file for some reason, will be corrected in the next release.
