### ISSUE TITLE
Module not listed in Manage Modules interface (Foundry 0.7.7)

### ISSUE THREAD

**Issue by kquinby** [zeel01/MonsterBlocks#31]
After installing MonsterBlocks from the Foundry Add-on interface, MonsterBlocks doesnt show up as an installed module that you can enable. Math.js does. Have tried uninstalling and reinstalling to no avail.

**Comment by zeel01** [comment]
What version of the 5e System is installed?

**Comment by kquinby** [comment]
0.99

**Comment by zeel01** [comment]
Please update 5e to 1.1.1
