### ISSUE TITLE
Generated Attack Descriptions problem

### ISSUE THREAD

**Issue by Pyroman2xxx** [zeel01/MonsterBlocks#4]
Great Mod.

I discovered one issue:

When "Generated Attack Descriptions" is enabled (which it is by default), it prevents the NPC window from closing and when I refresh the browser they disappear but I cannot reopen the sheet until I delete the token and create a new one.

I can still switch to the default NPC sheet using your macro but when I toggle back there is no sheet.

This may be related to other add-ons I have running, but all new tokens work perfectly when I disable the "Generated Attack Descriptions" setting.

**Comment by zeel01** [comment]
Are there any errors in the console? Typically the reason the sheet will fail to render is if there is an error encountered while building the template. If it's happening only if generated attack descriptions are enabled, it's most likely an issue with one of the Handlebars helpers used to calculate the stats of the attack.

Most likely there is another module using a Handlebars helper with the same name. Can you verify that this issue doesn't persist with other modules disabled?

**Comment by Pyroman2xxx** [comment]
Thank you for the reply. I did a little digging with the information you supplied and I have narrowed the issue.

There is a console error when rendering:

`foundry.js:3833 TypeError: An error occurred while rendering MonsterBlock5e 65: Cannot read property 'mod' of undefined
    at Object.getattackbonus (monsterblock.js:507)
    at Object.c (handlebars.min.js:27)
    at eval (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:19:161)
    at Object.h [as fn] (handlebars.min.js:27)
    at Object.<anonymous> (handlebars.min.js:27)
    at Object.c (handlebars.min.js:27)
    at eval (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:15:47)
    at Object.h [as fn] (handlebars.min.js:27)
    at Object.<anonymous> (handlebars.min.js:27)
    at Object.c (handlebars.min.js:27)
`
When testing I tried a different token and it worked with Attack Descriptions Enabled. Furthermore, the actual attack descriptions worked, which I did not realize they were not working on the former.

This seems to happen when the Weapon Attack ability modifer is set to "Default" rather than explicitly defined. I have tested and confirmed this.

I usually leave my tokens Attack modifier as default so they work with finesse.

**Comment by zeel01** [comment]
Fixed for v1.1.1
