### ISSUE TITLE
Skill and abilitychecks does not support shift/ctrl for advantage/disadvantage with better rolls.

### ISSUE THREAD

**Issue by DipsoNOR** [zeel01/MonsterBlocks#40]
Behaves as if I'm trying to select text. Rolls just a straight roll.

How to reproduce:
Have better rolls set to "Single Roll (Shift Advantage, Ctrl Disadvantage)"
Try to roll any skill or ability score with shift or ctrl pressed.

There are many abilities, skills and situations that imbue advantage / disadvantage on for instance perception or stealth rolls, so this is useful if can be done the same way as attack rolls.

**Comment by DipsoNOR** [comment]
UPDATE: it seems related to text selection. Some times if you have selected text it works.. sometimes.

Either way, it seems _very_ inconsistent. And might be related to a previous bug i reported where the problem just seemed to go away again on its own....

**Comment by zeel01** [comment]
Figured this one out, Better Rolls switched to `async` methods and I wasn't `await`ing the return from the advantage/disadvantage check. Should be good in the next release.
