### ISSUE TITLE
An incorrect translation key is used for attacks that have a non-attack "action type"

### ISSUE THREAD

**Issue by Moerill** [zeel01/MonsterBlocks#41]
![image](https://user-images.githubusercontent.com/26152015/102922536-77bf4280-448e-11eb-82a4-3584eb8f6344.png)

When you got an attack forcing a Saving Throw, the translation key is shown instead of the translation.

Correct wrong is `` DND5E.ActionSave``

Monster Blocks 2.4.3
DnD 1.2.0
FVTT 0.7.9

**Comment by zeel01** [comment]
Problem is, that's not really a valid "action type" for an attack. The rest of the formatted information is meaningless. There isn't a bonus to hit, 30 ft. is a *range* not a *reach*, etc.

I could likely make it find the correct translation string for this (actually I'm not totally sure why I'm looking it up the way I am, I need to take another look at that), but ultimately the result is still very much wrong.

I might be preferable to simply treat any "attack" that doesn't have one of the valid attack "action type"s as an "action" for purposes of display (it would not have the generated text at all).

I know there are some who would like to see some sort of generated data for options other than attack. There isn't a consistent format to employ for something like that though.

**Comment by zeel01** [comment]
For some reason I wasn't pulling these from `CONFIG.DND5E.itemActionTypes`, so I switched to that and now there should not be any translation strings leaking into places they don't belong. However the result is still very much *wrong*.
