### ISSUE TITLE
Compatibility with Combat Utility Belt's "Hide Actor Name" feature

### ISSUE THREAD

**Issue by jalensailin** [zeel01/MonsterBlocks#43]
CUB adds a little mask icon to character sheets which, when clicked, opens a settings dialogue to hide that actor's name in the Combat Tracker and Chat Cards.

I am hoping that this module be updated to have an option to display the mask icon if CUB is installed (or if that particular setting within CUB is enabled). Unless I am mistaken, currently one would have to switch sheets to the default, change the settings there, and then switch back to Monster Blocks. 

Thanks so much for a great and aesthetic mod!!

**Comment by zeel01** [comment]
This is somewhat tricky on my end. It would be more strait forward for CUB to make this change.

I can look into sending them a pull request with changes, but this is fairly low priority at the moment.

**Comment by jalensailin** [comment]
Understood, thanks for the quick response! Would it help if I put in an issue for the author of CUB?

**Comment by zeel01** [comment]
It couldn't hurt.

**Comment by zeel01** [comment]
It couldn't hurt.

**Comment by DipsoNOR** [comment]
I have already submitted an issue on the CUB git, by request of the developer. :)

https://github.com/death-save/combat-utility-belt/issues/446

**Comment by zeel01** [comment]
@DipsoNOR @jalensailin 

Any update on this issue? I don't use CUB personally so I'm not sure if this was ever resolved on that end.

**Comment by jalensailin** [comment]
@zeel01 Thanks for the reminder! It does seem to be fixed :). The developer moved the mask icon to the bar at the top of the sheet so that it is compatible with all sheets. Unfortunately, because the Monster Blocks sheet is very skinny compared to most sheets, that bar is very cramped and may not show all options if multiple modules utilize that space. This isn't your fault and seems more to be an issue with Core foundry not having a good way to deal with this situation. Thanks for checking in about it. Cheers!

**Comment by DipsoNOR** [comment]
> This isn't your fault and seems more to be an issue with Core foundry not having a good way to deal with this situation. Thanks for checking in about it. Cheers!

Hopefully it will get fixed in core eventually there is a issue for this currently open, and it seems pretty obvious that some sort of overflow menu needs to be made.
