### ISSUE TITLE
Feet / Miles selection box shows up even when editing is disabled.

### ISSUE THREAD

**Issue by DipsoNOR** [zeel01/MonsterBlocks#44]
At first I was really confused why the text "Feet" showed up when I mouse over speed and senses.

But after a bit of digging I found out that if you enable editing this text lets you choose between miles and feet.

It would probably make sense to not have this show up on a locked (un-editable) sheet. Especially since the the text doesn't really do anything then.

**Comment by zeel01** [comment]
Ah, yeah no, that shouldn't show up when not in editing mode. An oversight on my part.

**Comment by zeel01** [comment]
Fixed via https://github.com/zeel01/MonsterBlocks/commit/6484f5e050bdcdcfd06fc2bcec2feb236efce68c
