### ISSUE TITLE
Right click to edit tool tips should not appear if editing is disabled. 

### ISSUE THREAD

**Issue by jeremyregnerus** [zeel01/MonsterBlocks#45]
When you hover over the NPC image, there's a tooltip that appears to right click to edit the artwork. However, right mousing on the artwork doesn't do anything. If this is not the intended workflow, then this would be a great feature to mitigate the need to go into classic mode to edit the image.

**Comment by zeel01** [comment]
This should open the file picker dialog. Please check that you ha e editing enabled on your monster (check the cog menu in the upper left), and verify whether or not the issue persists when Monster Blocks is the *only* active module.

**Comment by jeremyregnerus** [comment]
Thank you, this was on me totally. I was not in edit mode. I was still seeing the tooltip for RMB in non-edit mode, and I think that's where the confusion was.

**Comment by zeel01** [comment]
Fixed via https://github.com/zeel01/MonsterBlocks/commit/d8aaf575c9d4b6f25efd8b2755b8402cec0cd462
