### ISSUE TITLE
Support continued text content on attacks

### ISSUE THREAD

**Issue by jeremyregnerus** [zeel01/MonsterBlocks#48]
Would be nice to recognize text in an attack description that starts with the *,* character to be a continuation of the default attack string that is created. An example would be as follows, where after the normal damage, there is an *, and* that follows the default text.
**Bite.** _Melee Weapon Attack:_ +5 to hit, reach 5 ft., one target. _Hit:_ 7 (1d8 + 3) piercing damage plus	9 (2d8) poison	damage, and target must make a DC 11 Constitution saving throw, taking 9 ( 2d8) poison damage on a failed save, or half as much damage on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, even after regaining hit points, and is paralyzed while poisoned in this way.

**Comment by zeel01** [comment]
Hmm, that's not a bad way of handling that case. I'll probably add this, I don't think it should be overly complicated, and I don't foresee any situation where someone would lead their description with a comma and *want* it to be preceded by a period. So it should be fine.

**Comment by jeremyregnerus** [comment]
I've verified that this works with your latest changes.

**Comment by zeel01** [comment]
I think this feature is working as intended now?
