### ISSUE TITLE
[Enhancement Request] New tags clutter generated attack descriptions.

### ISSUE THREAD

**Issue by JLtheking2** [zeel01/MonsterBlocks#52]
Hey! I've been happily using the generated attack descriptions, until a recent update where [prof] and [mod] tags started to show up in the generated attack descriptions.

![image](https://user-images.githubusercontent.com/48344299/107067846-d2ccaf00-681a-11eb-81fb-c01b1b2c394c.png)

The [prof] and [mod] tags are really distracting and clutter up the user interface. Is it possible to make disabling this behavior an option (or revert it to the way it was before)?

**Comment by zeel01** [comment]
Do these appear when Monster Blocks is the only module enabled?

Could you provide your Monster Blocks, dnd5e, and Foundry version numbers?

**Comment by JLtheking2** [comment]
My bad - I should have checked to isolate what mod was causing the issue.

It seems to be a conflict with Mars (https://github.com/Moerill/fvtt-mars-5e). With that mod deactivated Monster Blocks works normally. I'll close the issue for now and file an issue there.
