### ISSUE TITLE
[Bug] Icon to change to Monster Block no longer showing up

### ISSUE THREAD

**Issue by comsnath** [zeel01/MonsterBlocks#53]
I've noticed a strange bug where I am unable to change monsters to their Monster Block counterpart. The gear icon isn't showing up, nor is the module showing in the settings, however, is shown to be installed in the setup. I've attempted disabling all my modules to see if there was a conflict, but that also didn't work.

Love your work! It makes running monsters so much easier.

![image](https://user-images.githubusercontent.com/60007620/107472469-4416a580-6b2c-11eb-8c6a-05ba84ebf5de.png)
![image](https://user-images.githubusercontent.com/60007620/107472498-4e38a400-6b2c-11eb-8727-316452d4ec56.png)
![image](https://user-images.githubusercontent.com/60007620/107472530-5f81b080-6b2c-11eb-93ca-8dc33d27393f.png)
![image](https://user-images.githubusercontent.com/60007620/107472718-b2f3fe80-6b2c-11eb-951b-44c8ca6336be.png)

**Comment by zeel01** [comment]
What version of `dnd5e` do you have installed?

**Comment by comsnath** [comment]
That was the issue. I was running 1.2.0, not the latest 1.2.4. That also fixed my issue where the BetterRolls for 5E had also disappeared. Thanks for that! I'll make sure to update both the modules and the game system next time.
