### ISSUE TITLE
Attacks show +0 to hit?

### ISSUE THREAD

**Issue by Ekrizdis367** [zeel01/MonsterBlocks#59]
For some reason attacks are showing +0 to hit, but if actually rolled, they roll the appropriate modifiers (Ability Modifier + Challenge Rating Modifier).

**Comment by zeel01** [comment]
Is this effecting all attacks and all creatures? Does this happen when Monster Blocks is the only module enabled? What version of Monster Blocks, dnd5e, and Foundry are you running?

**Comment by zeel01** [comment]
Solved: Outdated Dynamic Effect module
