### ISSUE TITLE
Innate Spellcasting

### ISSUE THREAD

**Issue by Ekrizdis367** [zeel01/MonsterBlocks#60]
When trying to add Innate Spellcasting to a new creature it tries to automatically fill it in? But you can't change what it fills in? And it won't display the list of spells. It cuts off the actual spell list.

**Comment by zeel01** [comment]
You can disable the generated spellcasting feature.

Spells will appear below the generated text if they are marked as innate spells (in their preparation mode). Spells that aren't marked as innate will not appear in the innate spellcasting list.

**Comment by Ekrizdis367** [comment]
Thanks, that worked for properly displaying all text in Innate Spellcasting. Sorry about that.
