### ISSUE TITLE
Double check compatibility with DF Manual Rolls

### ISSUE THREAD

**Issue by plutoneld** [zeel01/MonsterBlocks#64]
"There seems to be an incompatibility with Monster Blocks and DF Manual Rolls. Every dice expression within parenthesis generates a dialog [from DF Manual Rolls] when the sheet is simply opened. No actual rolls are done though."

Likely culprit is DF Manual Rolls ignoring max rolls but not min rolls, according to flamewave000

Discord discussion starts here: https://discord.com/channels/170995199584108546/722566083499786352/817466768699424830

**Comment by zeel01** [comment]
Is there still an issue? I never had time to check this, so if there is still a problem and no additional complaints in all this time I probably don't have the bandwidth to work on it.

**Comment by plutoneld** [comment]
This was indeed an error on DF Manual Rolls part and was fixed in a subsequent release. I see no compatibility errors between the two modules as of now.
