### ISSUE TITLE
Icons on top bar hidden - Is a resizable window possible?

### ISSUE THREAD

**Issue by nulmas** [zeel01/MonsterBlocks#67]
Depending on the monster, sometimes icons that should be on the top bar become hidden.

Would it be possible to implement a resizable windows? In this example, not only is the creature's name partially hidden, but there are other icons missing, like the Token Preferences.
![mm](https://user-images.githubusercontent.com/79886727/110950497-d1236900-833b-11eb-9731-9a6c1a5a9a7a.jpg)

**Comment by zeel01** [comment]
Unfortunately it is not feasible to make the sheet resizable given the layout restrictions.

The top bar icon problem is something that's supposed to be addressed in the future by a Foundry core update. For the time being, it is possible to improve a bit with Custom CSS.

**Comment by figotech** [comment]
Using the Compact Window option in MonsterBlocks helps alleviate the problem, and IMO looks waaaaaay better.

**Comment by nulmas** [comment]
Thanks, @figotech! That worked wonderfully!
