### ISSUE TITLE
Bug when switching sheet through cog icon

### ISSUE THREAD

**Issue by nulmas** [zeel01/MonsterBlocks#68]
When switching to/from a monster blocks sheet through the cog icon, the new sheet will not be of the token itself but of the prototype token. Subsequent switches will stay on the prototype token sheet.
![token](https://user-images.githubusercontent.com/79886727/110951270-cb7a5300-833c-11eb-801d-08a3255b3dc4.jpg)
![prot token](https://user-images.githubusercontent.com/79886727/110951303-d46b2480-833c-11eb-8f57-512e8cd1a336.jpg)

**Comment by zeel01** [comment]
That is... odd. However, this appears to be a problem with the core software not with Monster Blocks specifically. All that button does is change the configured sheet class for the actor, the rest is handled by Foundry.
