### ISSUE TITLE
Typo in Legendary Actions Text

### ISSUE THREAD

**Issue by DivertedCircle** [zeel01/MonsterBlocks#69]
The word 'choosing' in the Legendary Actions description is incorrectly spelled as 'chooseing'.

**Comment by zeel01** [comment]
Oops! Thanks for the report.

**Comment by zeel01** [comment]
Fixed via https://github.com/zeel01/MonsterBlocks/commit/9df715fd49f1f12c0f5905ba405559f99a6426e3
