### ISSUE TITLE
Proficient saving throws not working

### ISSUE THREAD

**Issue by Pyroman2xxx** [zeel01/MonsterBlocks#7]
Found one issue since the last patch:

Monsters with proficient saving throws show the link when hovered over, but do not generate a saving throw roll when clicked.

**Comment by zeel01** [comment]
Are you saying that clicking of these is not rolling a save? 
![Screenshot_20200806-143429~2](https://user-images.githubusercontent.com/1721836/89568999-1ace3300-d7f2-11ea-81ac-9a3ebb71792d.png)

**Comment by Pyroman2xxx** [comment]
> 
> 
> Are you saying that clicking one of these is not rolling a save?
> ![Screenshot_20200806-143429~2](https://user-images.githubusercontent.com/1721836/89568999-1ace3300-d7f2-11ea-81ac-9a3ebb71792d.png)

That is correct. The skills do work, it is just the saving throws for some reason. Since you cannot reproduce, I will continue to look into what may be happening.  Thank you!

**Comment by zeel01** [comment]
Are any errors generated in the console? Are you using Better Rolls or default rolls?

Can you verify that this issue persists for you when Monster Blocks is the only module enabled?

**Comment by Pyroman2xxx** [comment]
Ok, I found the issue.

It is an incompatibility with the MESS (Moerills enhancing super-suite) add-on, "Alternative rolling and targetting" function:
```
Uncaught TypeError: Cannot read property 'dataset' of null
    at HTMLSpanElement.<anonymous> (modules/mess/scripts/index.js:57)
foundry.js:3855 Foundry VTT | Rendering a
modify-rolling.js:297 Uncaught TypeError: Cannot read property 'dataset' of null
    at HTMLSpanElement.<anonymous> (modify-rolling.js:297)
```

I have confirmed that disabling the Alternative rolling and targetting option in that add-on allows saves to work normally.
