### ISSUE TITLE
Spellcasting only shows Cantrips

### ISSUE THREAD

**Issue by aodnightshade** [zeel01/MonsterBlocks#77]
So sporadically the "spellcasting" feature will only get cantrips and no other spells. Here is an example of when it worked and didn't work: 

![](https://puu.sh/HKcFg/bbeb707960.png)

**Comment by zeel01** [comment]
Does this only happen on Warlocks? Their spells use pact magic, so you might need to reconfigure your spells and/or casting ability to see them listed properly.

**Comment by aodnightshade** [comment]
Okay I believe I figured out the issue in question. I needed to add all the spells first before making the feat. If I created the feat before that then I needed to delete the feat and make a new one. So it had a specific order of operations for me.
