### ISSUE TITLE
Default theme does not apply

### ISSUE THREAD

**Issue by Zamrod** [zeel01/MonsterBlocks#81]
Setting the default theme has no effect.

Foundry 0.8.6
Monster Blocks 3.0.0
math,js 7.5.1--fvtt2
DnD5e 1.3.3

-Created a brand new world.
-Enabled Monster Blocks and math.js
-Set the default theme to Icy Breeze
-Created a new NPC called "Test Monster"
-Switched sheet to Monster Blocks
-It shows the default Monster Manual theme
-Closed and reopened the character sheet, no change

-Reset to Defaults does change its theme though.

**Comment by zeel01** [comment]
Fixed via https://github.com/zeel01/MonsterBlocks/commit/46b491a9ba91fcac82c071213e8c21a02e5b7a1a
