### ISSUE TITLE
Settings #6-10 are missing descriptions

### ISSUE THREAD

**Issue by chklein1** [zeel01/MonsterBlocks#82]
After upgrading to Foundry 0.8.6 + DnD5e 1.3.3 + Monster Blocks 3.0.0, the text associated with settings #6-10 from the top of the list is missing. For example, setting #6 shows "MOBLOKS5E.compact-window-name" as the name and "MOBLOKS5E.compact-window-hint" as the description. The show bio setting has the same issue. The issue didn't repro on previous versions running under Foundry 0.7.9.
![Screenshot](https://user-images.githubusercontent.com/85462739/120942964-ec0a3d00-c6e0-11eb-8567-6992ee092221.png)

**Comment by zeel01** [comment]
Fixed via https://github.com/zeel01/MonsterBlocks/commit/9688ae32c96f8028876c2976687acf804e0b5dfe
