### ISSUE TITLE
Not sure what issue is, doesn't work at all. 

### ISSUE THREAD

**Issue by jquickri** [zeel01/MonsterBlocks#84]
So I've used this module in 7th edition and really liked it but I can't get it working at all right now. 

I completely disabled all other modules and still can't get it to do anything. Not sure what other information I should provide but if you need anything to help I'll try and provide it.

**Comment by jquickri** [comment]
Okay messed around with it a bit and figured out I can switch to the monster sheet by clicking on the sheet option for a character. Is there a way to make your option the default option when I open a monster? Apologies if this is an inappropriate place to post this.

**Comment by zeel01** [comment]
The sheet options dialog also has a selector for the "default" sheet, this can be used to make all NPCs open in this sheet.
