### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by eolias78** [zeel01/MonsterBlocks#86]
Hi,

Thank you for you module. I've just made a french translation of it. How can I send it to you ?

Best regards

**Comment by zeel01** [comment]
Hey there, that's awesome! If you are familiar with the Pull Request feature, you can use that, otherwise just attach your new JSON file to this issue and I'll add it to the next release!

Thank you for pitching in 😊

**Comment by eolias78** [comment]
I don't know the pull feature. So, I prefer attaching my translation here ;)

[fr.zip](https://github.com/zeel01/MonsterBlocks/files/6644166/fr.zip)

**Comment by zeel01** [comment]
Added via https://github.com/zeel01/MonsterBlocks/commit/66110cbcb4f3716a0ca2295d59627c140bb192bc
