### ISSUE TITLE
Localization string issue

### ISSUE THREAD

**Issue by Norc** [zeel01/MonsterBlocks#87]
![image](https://user-images.githubusercontent.com/64667579/121852273-409f5080-ccbd-11eb-8dfe-9b77f4117109.png)

**Comment by Norc** [comment]
also show-bio-name lower down is showing up "raw" as well.

**Comment by zeel01** [comment]
Fixed via https://github.com/zeel01/MonsterBlocks/commit/9688ae32c96f8028876c2976687acf804e0b5dfe
