### ISSUE TITLE
with devMode module enabled, monsterblock sheet fails to render

### ISSUE THREAD

**Issue by akrigline** [zeel01/MonsterBlocks#89]
In your `debug` class, this static method:
```js
	static get enabled() {
		return window.DEV?.getPackageDebugValue("monsterblock");
	}
```
is throwing an error because monsterblock does not register a 'boolean' debug flag, only a `level` one.

I'm not 100% what you're looking to do with this, might be you're trying to tell if `level > 0`?

**Comment by zeel01** [comment]
Idk man, it worked in 0.7, but I soooo don't remember what the debug code I wrote does.
