### ISSUE TITLE
Add Biography and make AC editable

### ISSUE THREAD

**Issue by figotech** [zeel01/MonsterBlocks#9]
Hi, I LOVE the way your mod makes the monster sheets look. I have 2 suggestions:
1) Add a biography button: the way Some monsters are imported (specially from Roll20) have all the info from the MM in the BIography. Being able to quickly check it is something I miss when using the monster sheets. It could be at the top bar or a small link near the portrait.

2) If you are just going to make a couple of stuff editable please make AC one of them.  I use  a lot Foundry's targetting system with autoapply damage, and sometimes an enemy may pickup a shield, or have Magic armor cast... stuff like that where I need a quick AC edit so the calculations are correct.

**Comment by zeel01** [comment]
Both of these are planned. The next big focus I'm working on editing, so AC is already possible to edit on the v2.x branch (very alpha). The bio is something I need to figure out how best to deal with, but it's something I do intend to make available.

**Comment by KageJittai** [comment]
This is required for supporting "Limited" access previews, which show the Bio but not the stat block. Very useful for NPCs where you want the players to see some details about the sheet but not others. Limited access should also hide "Secret" blocks inside of the bio.
