### ISSUE TITLE
Can't find Tokenizer access from NPC Sheet

### ISSUE THREAD

**Issue by eolias78** [zeel01/MonsterBlocks#90]
Hi,

While translating your module, I saw there is a VTTA Tokenizer button or something like that ? Could you tell me how to use this feature. When I click on creature image, it opens it. I have to switch to default sheet to open Tokenizer.

Best regards

**Comment by zeel01** [comment]
The Tokenizer button is in the cog menu in the upper left corner. If the VTTA Tokenizer module is installed, a new option will appear in that menu.
