### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by eolias78** [zeel01/MonsterBlocks#91]
Hi,

I've just checked the translation I sent you on my Forge server. I may have made a mistake cause Multiattack and spell automations don't work.

Another question before leaving : could you add a translation field for ft, plz ? In France, we use meters and it would be so great to have it ingame 👍

**Comment by zeel01** [comment]
Unit translations are not handled by Monster Blocks, it just displays the units that the system provides. I believe there might be a module that changes the units specifically, but I don't recall what it was.

**Comment by eolias78** [comment]
[fr.zip](https://github.com/zeel01/MonsterBlocks/files/6704617/fr.zip)
