### ISSUE TITLE
Can't hide Biography in 0.8.8 Foundry

### ISSUE THREAD

**Issue by Havoclivekiller** [zeel01/MonsterBlocks#95]
I click Hide Biography and nothing happens. Turned off all modules, only Monster Blocks is on and the issue persisted.

**Comment by zeel01** [comment]
Can you confirm what version of Monster Blocks you are using? This was an issue I thought was already resolved.

If the issue persists on the latest version, please check for errors in the console.

**Comment by Havoclivekiller** [comment]
3.0.1
Only old actors have this problem it seems. I don't know why.
![image](https://user-images.githubusercontent.com/21118924/129065637-b722619d-9021-4eb0-aaf6-2ec5e6f6bc28.png)
[fvtt-Actor-zuglar-urnfurnace.zip](https://github.com/zeel01/MonsterBlocks/files/6969912/fvtt-Actor-zuglar-urnfurnace.zip)

**Comment by zeel01** [comment]
Try clicking reset to defaults?

**Comment by Havoclivekiller** [comment]
It did nothing. Tried clicking others, none would allow me to switch.

**Comment by zeel01** [comment]
Can you check the console for errors? I tested with the Actor you provided and was not able to reproduce this issue.

Also, you might want to test with all modules other than Monster Blocks disabled.

**Comment by Havoclivekiller** [comment]
Strange. No errors. Before making the issue, I've tested with only Monster Blocks enabled (find the culprit).

**Comment by zeel01** [comment]
I released a new version yesterday, I don't know if it will make a difference, but it's worth a try to test it.

**Comment by zeel01** [comment]
Unfortunately I'm still not able to reproduce this issue.

If you can capture an error message that might help me track it down, feel free to re-open.
