### ISSUE TITLE
Ability to hide non-essential descriptions

### ISSUE THREAD

**Issue by maxobremer** [zeel01/MonsterBlocks#99]
It would be nice to have the feature to completely hide the description of items within the inventory section of the sheet and have it as a toggle per item for everything else. 
Would also be nice to have a toggle for stuff that takes an action or the compact feature mode per category, aka features. actions (with maybe the exception for hiding the generated attack description) and inventory.

Good work so far, keep it up 👍

**Comment by zeel01** [comment]
Superseded by #163, #164, and `compact-features`.
